language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: klojure-docs/target/doc
  target-branch: gh-pages
  on:
    branch: master
