language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
  - mvn clojure:run -Dclojure.script=src/main/clojure/doc/main.clj
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/doc
  target-branch: gh-pages
  on:
    branch: master
