language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
branches:
  only:
  - master
# TODO - Fix docs (https://github.com/djblue/klojure/issues/10)
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: target/doc
#  target-branch: gh-pages
#  on:
#    branch: master
